baseURL = 'https://playingfutures.today/'
languageCode = 'en-us'
title = 'Playing Futures Conference'
theme = 'hello-friend-ng'

[params]
defaultTheme = "auto"
showReadingTime = false
showPostNavLinks = true

[params.Logo]
logoText = "Playing Futures"

[params.footer]
bottomText = [
  'Hosted on <a href="https://1984.hosting" target="_blank" rel="noopener">1984.hosting</a>',
  'Built with <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a>'
]

[menu]
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 20
[[menu.main]]
identifier = "current"
name = "Current Conference"
url = "/conferences/2026/"
weight = 25
[[menu.main]]
identifier = "cfp"
name = "Call for Papers"
url = "/call-for-papers/"
weight = 30
[[menu.main]]
identifier = "conferences"
name = "Archive"
url = "/conferences/"
weight = 50
